"""empty message

Revision ID: 2cc417f6c642
Revises: e038459351c8
Create Date: 2022-03-19 17:30:11.327903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc417f6c642'
down_revision = 'e038459351c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'login_history', ['id', 'created_at'])
    op.create_unique_constraint(None, 'roles', ['id'])
    op.create_unique_constraint(None, 'roles_relations', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'roles_relations', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'login_history', type_='unique')
    # ### end Alembic commands ###
